# Generated by Django 5.1.2 on 2024-11-16 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_color_product'),
        ('pos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbounditem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorylocation'),
        ),
    ]
