# Generated by Django 5.1.2 on 2024-12-28 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorylocation_reserved'),
        ('pos', '0004_inbounditem_inventory_outbounditem_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbounditem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbounditem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stock'),
        ),
        migrations.AlterUniqueTogether(
            name='inbounditem',
            unique_together={('material', 'inbound')},
        ),
    ]
