# Generated by Django 5.1.2 on 2024-12-29 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorylocation_reserved'),
        ('pos', '0006_remove_inbounditem_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbounditem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorylocation'),
        ),
    ]
