# Generated by Django 5.1.2 on 2024-12-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_inbounditem_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inbounditem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='inbounditem',
            name='location',
        ),
    ]
