# Generated by Django 5.1.2 on 2024-12-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_inbounditem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbounditem',
            name='inventory',
        ),
    ]
