# Generated by Django 5.1.2 on 2024-11-08 09:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rgb', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors',
            },
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rows_number', models.IntegerField()),
                ('columns_number', models.IntegerField()),
                ('layers_number', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description1', models.TextField(null=True)),
                ('description2', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='stock_images/')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('m', 'Meter'), ('each', 'Each')], max_length=255, null=True)),
                ('unit_cost', models.FloatField(blank=True, null=True)),
                ('stocks_on_hand', models.IntegerField(default=0)),
                ('stocks_committed', models.IntegerField(default=0)),
                ('stocks_availability', models.IntegerField(editable=False)),
                ('stored_stocks', models.IntegerField(default=0)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('sold_number', models.IntegerField(default=0)),
                ('threshold', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(null=True)),
                ('column', models.IntegerField(null=True)),
                ('layer', models.IntegerField(null=True)),
                ('quantity', models.FloatField(blank=True, default=0, null=True)),
                ('reserved', models.BooleanField(default=True, null=True)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
            ],
            options={
                'unique_together': {('inventory', 'row', 'column', 'layer')},
            },
        ),
    ]
