# Generated by Django 5.1.2 on 2024-12-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorylocation_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylocation',
            name='reserved',
            field=models.BooleanField(null=True),
        ),
    ]
