# Generated by Django 5.1.2 on 2024-12-30 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorylocation_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
