# Generated by Django 5.1.2 on 2024-12-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stock_inventory_stock_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylocation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventorylocation',
            name='stock',
        ),
    ]
