# Generated by Django 5.1.2 on 2024-11-16 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0009_order_seen_by_user'),
        ('sales', '0002_remove_materialreport_inbound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialreport',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_commerce.order'),
        ),
    ]
